# ❌ version: "3.9"  ← ya no se usa, se elimina

services:
  auth:
    build: ./auth-service
    container_name: auth_service
    restart: always
    environment:
      - SECRET_KEY=super_secret_key_123
      - DEBUG=1
      - DB_HOST=postgres
      - DB_NAME=main_db
      - DB_USER=devuser
      - DB_PASS=devpass
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"

  auth-client:
    build: ./auth-client
    container_name: auth_client
    ports:
      - "5175:5173"   # puerto del navegador
    depends_on:
      - auth  # ✅ corregido: coincide con el nombre real del servicio backend
    environment:
      - VITE_API_URL=http://auth:8000/api  # ✅ frontend hablará con Django dentro de la red Docker

  blog_client:
    build: ./blog-client
    container_name: blog_client
    ports:
      - "5173:90"  # Frontend accesible en http://localhost:5173
    depends_on:
      - auth
  postgres:
    image: postgres:15
    container_name: db_postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: cache_redis
    restart: always
    env_file:
      - .env
    ports:
      - "${REDIS_PORT:-6379}:6379"

      

volumes:
  pgdata:
